# Site id should be the same as GitHub repository name. Ids are case-sensitive.

test:
  from: git@github.com:dreikanter/jekyll-test.git
  to: pusher@softtiny.com:/var/www/test.spybo.at/current/public/

softtinyco:
  from: git@github.com:softtinyco/softtiny.com.git
  to: pusher@softtiny.com:/var/www/softtiny.com/current/public/

darky:
  from: git@github.com:DarkDeny/darky.softtiny.com.git
  to: pusher@softtiny.com:/var/www/darky.softtiny.com/current/public/
